#!/usr/bin/env bundle exec ruby
# This script can only be run from elsewhere if BUNDLE_GEMFILE of this project
# has been set.

require "advent_of_code"
AdventOfCode::Shell.run(ARGV, out: $stdout, err: $stderr) do |options|
  AdventOfCode::DoSomething.new(options, out: $stdout, err: $stderr).show
end
